### ISSUE TITLE
Wrong foreign keys and missing schemas in datapackage

### ISSUE THREAD

**Issue by henhuy** [OpenEnergyPlatform/oedatamodel#16]
I tried to create ORM from metadata file (via https://github.com/OpenEnergyPlatform/oem2orm), but this failed due several minor things:
- schema not given in FK
- wrong PK/FK name in data table (scenario/data IDs switched)
- invalid types (for oem2orm) "hstore", "decimal"
- array[float] has to be written as float array in oem2orm (to be discussed!, as this looks not nice)

**Comment by jh-RLI** [comment]
Thats great :) Good Work, I will include this in the oedatamodel and will create a tutorial on how to use eralchemy.

**Comment by jh-RLI** [comment]
Fixed in linked PR. Include fixes in the concrete and inheritance data model.
