### ISSUE TITLE
No column "id" in tables of oedatamodel

### ISSUE THREAD

**Issue by henhuy** [OpenEnergyPlatform/oedatamodel#26]
Just wanted to post data into our oeddatamodel but upload fails with following response:
_reason": "column \\"id\\" does not exist"_

From https://oep-data-interface.readthedocs.io/en/latest/api/how_to.html#create-table it states, that tables have to have a primary key called "id". Thus, we have to change "scenario_id" in table "oed_scenario" to "id" (and all other tables). Unfortunately, there is no error message when creating the table without column "id" - maybe there should be one?!

**Comment by jh-RLI** [comment]
That is unfortunate. I usually only uploaded data with pandas. That way it works without an ID column, if I'm not mistaken. I did not notice this issue.
